チャンネルソート機能の追加
nattyan-tv/tensei_disko pull request #47
Opened 2023-05-03 15:11 UTC by nattyan-tv

# 概要
説　明　不　要

ただチャンネルをクイックソートして、Unicodeのコードポイント順に並べるだけの機能

# そういえば
1日ぐらい寝かせたら勝手にマージしよーっと（( ˘ω˘ )）

2023-05-03 17:14 UTC, CrystalAlpha358 requested changes
誤字とかバグになりそうなものとか

2023-05-03 17:14 UTC, CrystalAlpha358 commented on cogs/channel_sort.py
> +        優位条件3: それ以外の場合、チャンネルは同じと判断されるため、aをが優位とされる
誤字  
...ため、a `をが`...

2023-05-03 17:14 UTC, CrystalAlpha358 commented on cogs/channel_sort.py
> +            category = interaction.channel.category
カテゴリの外にあるチャンネルを考慮していない（`interaction.channel.category` は `None` になり得る）

2023-05-03 17:14 UTC, CrystalAlpha358 commented on cogs/channel_sort.py
> +        ),
`required=False` かつ `default` が無いので型ヒントは `nextcord.CategoryChannel | None`

2023-05-03 17:14 UTC, CrystalAlpha358 commented on cogs/channel_sort.py
> +        await interaction.response.defer()
この辺りに `assert interaction.channel is not None` と書いておくと以後不要な型周りの警告を減らせる（任意だけど）

2023-05-03 17:14 UTC, CrystalAlpha358 commented on cogs/channel_sort.py
> +            return
コマンド内部でチェックするのではなく [`@nextcord.ext.application_checks.guild_only`](https://docs.nextcord.dev/en/stable/ext/application_checks/index.html#nextcord.ext.application_checks.guild_only) デコレータを使う  
`assert not isinstance(interaction.channel, nextcord.PartialMessageable)` を追加すれば型の警告を消せる（任意）

※ `DMChannel` ではなく `PartialMessageable` な理由は[ここ](https://docs.nextcord.dev/en/stable/api.html#nextcord.Interaction.channel)を参照

2023-05-04 04:54 UTC, nattyan-tv commented
これで良いんだっけ（記憶喪失のPR初心者）

2023-05-04 05:47 UTC, CrystalAlpha358 approved these changes
コードの整形と型周りを調整した  
他は LGTM

2023-05-04 05:49 UTC, merged